
export type Country = {
  name: string;
  flag: string;
  code: string;
  dial_code: string;
  minLength: number;
  maxLength: number;
};

export const countries: Country[] = [
    { name: 'Afghanistan', flag: '/flags/afg.png', code: 'AF', dial_code: '+93', minLength: 9, maxLength: 9 },
    { name: 'Åland Islands', flag: '/flags/ala.png', code: 'AX', dial_code: '+358', minLength: 9, maxLength: 9 },
    { name: 'Albania', flag: '/flags/alb.png', code: 'AL', dial_code: '+355', minLength: 9, maxLength: 9 },
    { name: 'Algeria', flag: '/flags/dza.png', code: 'DZ', dial_code: '+213', minLength: 9, maxLength: 9 },
    { name: 'American Samoa', flag: '/flags/asm.png', code: 'AS', dial_code: '+1684', minLength: 7, maxLength: 7 },
    { name: 'Andorra', flag: '/flags/and.png', code: 'AD', dial_code: '+376', minLength: 6, maxLength: 6 },
    { name: 'Angola', flag: '/flags/ago.png', code: 'AO', dial_code: '+244', minLength: 9, maxLength: 9 },
    { name: 'Anguilla', flag: '/flags/aia.png', code: 'AI', dial_code: '+1264', minLength: 7, maxLength: 7 },
    { name: 'Antarctica', flag: '/flags/ata.png', code: 'AQ', dial_code: '+672', minLength: 6, maxLength: 6 },
    { name: 'Antigua and Barbuda', flag: '/flags/atg.png', code: 'AG', dial_code: '+1268', minLength: 7, maxLength: 7 },
    { name: 'Argentina', flag: '/flags/arg.png', code: 'AR', dial_code: '+54', minLength: 10, maxLength: 10 },
    { name: 'Armenia', flag: '/flags/arm.png', code: 'AM', dial_code: '+374', minLength: 8, maxLength: 8 },
    { name: 'Aruba', flag: '/flags/abw.png', code: 'AW', dial_code: '+297', minLength: 7, maxLength: 7 },
    { name: 'Australia', flag: '/flags/aus.png', code: 'AU', dial_code: '+61', minLength: 9, maxLength: 9 },
    { name: 'Austria', flag: '/flags/aut.png', code: 'AT', dial_code: '+43', minLength: 10, maxLength: 13 },
    { name: 'Azerbaijan', flag: '/flags/aze.png', code: 'AZ', dial_code: '+994', minLength: 9, maxLength: 9 },
    { name: 'Bahamas', flag: '/flags/bhs.png', code: 'BS', dial_code: '+1242', minLength: 7, maxLength: 7 },
    { name: 'Bahrain', flag: '/flags/bhr.png', code: 'BH', dial_code: '+973', minLength: 8, maxLength: 8 },
    { name: 'Bangladesh', flag: '/flags/bgd.png', code: 'BD', dial_code: '+880', minLength: 10, maxLength: 10 },
    { name: 'Barbados', flag: '/flags/brb.png', code: 'BB', dial_code: '+1246', minLength: 7, maxLength: 7 },
    { name: 'Belarus', flag: '/flags/blr.png', code: 'BY', dial_code: '+375', minLength: 9, maxLength: 9 },
    { name: 'Belgium', flag: '/flags/bel.png', code: 'BE', dial_code: '+32', minLength: 9, maxLength: 9 },
    { name: 'Belize', flag: '/flags/blz.png', code: 'BZ', dial_code: '+501', minLength: 7, maxLength: 7 },
    { name: 'Benin', flag: '/flags/ben.png', code: 'BJ', dial_code: '+229', minLength: 8, maxLength: 8 },
    { name: 'Bermuda', flag: '/flags/bmu.png', code: 'BM', dial_code: '+1441', minLength: 7, maxLength: 7 },
    { name: 'Bhutan', flag: '/flags/btn.png', code: 'BT', dial_code: '+975', minLength: 8, maxLength: 8 },
    { name: 'Bolivia', flag: '/flags/bol.png', code: 'BO', dial_code: '+591', minLength: 8, maxLength: 8 },
    { name: 'Bosnia and Herzegovina', flag: '/flags/bih.png', code: 'BA', dial_code: '+387', minLength: 8, maxLength: 8 },
    { name: 'Botswana', flag: '/flags/bwa.png', code: 'BW', dial_code: '+267', minLength: 7, maxLength: 8 },
    { name: 'Brazil', flag: '/flags/bra.png', code: 'BR', dial_code: '+55', minLength: 11, maxLength: 11 },
    { name: 'British Indian Ocean Territory', flag: '/flags/iot.png', code: 'IO', dial_code: '+246', minLength: 7, maxLength: 7 },
    { name: 'Brunei Darussalam', flag: '/flags/brn.png', code: 'BN', dial_code: '+673', minLength: 7, maxLength: 7 },
    { name: 'Bulgaria', flag: '/flags/bgr.png', code: 'BG', dial_code: '+359', minLength: 9, maxLength: 9 },
    { name: 'Burkina Faso', flag: '/flags/bfa.png', code: 'BF', dial_code: '+226', minLength: 8, maxLength: 8 },
    { name: 'Burundi', flag: '/flags/bdi.png', code: 'BI', dial_code: '+257', minLength: 8, maxLength: 8 },
    { name: 'Cambodia', flag: '/flags/khm.png', code: 'KH', dial_code: '+855', minLength: 9, maxLength: 9 },
    { name: 'Cameroon', flag: '/flags/cmr.png', code: 'CM', dial_code: '+237', minLength: 9, maxLength: 9 },
    { name: 'Canada', flag: '/flags/can.png', code: 'CA', dial_code: '+1', minLength: 10, maxLength: 10 },
    { name: 'Cape Verde', flag: '/flags/cpv.png', code: 'CV', dial_code: '+238', minLength: 7, maxLength: 7 },
    { name: 'Cayman Islands', flag: '/flags/cym.png', code: 'KY', dial_code: '+1345', minLength: 7, maxLength: 7 },
    { name: 'Central African Republic', flag: '/flags/caf.png', code: 'CF', dial_code: '+236', minLength: 8, maxLength: 8 },
    { name: 'Chad', flag: '/flags/tcd.png', code: 'TD', dial_code: '+235', minLength: 8, maxLength: 8 },
    { name: 'Chile', flag: '/flags/chl.png', code: 'CL', dial_code: '+56', minLength: 9, maxLength: 9 },
    { name: 'China', flag: '/flags/chn.png', code: 'CN', dial_code: '+86', minLength: 11, maxLength: 11 },
    { name: 'Christmas Island', flag: '/flags/cxr.png', code: 'CX', dial_code: '+61', minLength: 9, maxLength: 9 },
    { name: 'Cocos (Keeling) Islands', flag: '/flags/cck.png', code: 'CC', dial_code: '+61', minLength: 9, maxLength: 9 },
    { name: 'Colombia', flag: '/flags/col.png', code: 'CO', dial_code: '+57', minLength: 10, maxLength: 10 },
    { name: 'Comoros', flag: '/flags/com.png', code: 'KM', dial_code: '+269', minLength: 7, maxLength: 7 },
    { name: 'Congo', flag: '/flags/cog.png', code: 'CG', dial_code: '+242', minLength: 9, maxLength: 9 },
    { name: 'Congo, The Democratic Republic of the', flag: '/flags/cod.png', code: 'CD', dial_code: '+243', minLength: 9, maxLength: 9 },
    { name: 'Cook Islands', flag: '/flags/cok.png', code: 'CK', dial_code: '+682', minLength: 5, maxLength: 5 },
    { name: 'Costa Rica', flag: '/flags/cri.png', code: 'CR', dial_code: '+506', minLength: 8, maxLength: 8 },
    { name: "Cote D'Ivoire", flag: '/flags/civ.png', code: 'CI', dial_code: '+225', minLength: 10, maxLength: 10 },
    { name: 'Croatia', flag: '/flags/hrv.png', code: 'HR', dial_code: '+385', minLength: 9, maxLength: 9 },
    { name: 'Cuba', flag: '/flags/cub.png', code: 'CU', dial_code: '+53', minLength: 8, maxLength: 8 },
    { name: 'Cyprus', flag: '/flags/cyp.png', code: 'CY', dial_code: '+357', minLength: 8, maxLength: 8 },
    { name: 'Czech Republic', flag: '/flags/cze.png', code: 'CZ', dial_code: '+420', minLength: 9, maxLength: 9 },
    { name: 'Denmark', flag: '/flags/dnk.png', code: 'DK', dial_code: '+45', minLength: 8, maxLength: 8 },
    { name: 'Djibouti', flag: '/flags/dji.png', code: 'DJ', dial_code: '+253', minLength: 6, maxLength: 6 },
    { name: 'Dominica', flag: '/flags/dma.png', code: 'DM', dial_code: '+1767', minLength: 7, maxLength: 7 },
    { name: 'Dominican Republic', flag: '/flags/dom.png', code: 'DO', dial_code: '+1809', minLength: 10, maxLength: 10 },
    { name: 'Ecuador', flag: '/flags/ecu.png', code: 'EC', dial_code: '+593', minLength: 9, maxLength: 9 },
    { name: 'Egypt', flag: '/flags/egy.png', code: 'EG', dial_code: '+20', minLength: 10, maxLength: 10 },
    { name: 'El Salvador', flag: '/flags/slv.png', code: 'SV', dial_code: '+503', minLength: 8, maxLength: 8 },
    { name: 'Equatorial Guinea', flag: '/flags/gnq.png', code: 'GQ', dial_code: '+240', minLength: 9, maxLength: 9 },
    { name: 'Eritrea', flag: '/flags/eri.png', code: 'ER', dial_code: '+291', minLength: 7, maxLength: 7 },
    { name: 'Estonia', flag: '/flags/est.png', code: 'EE', dial_code: '+372', minLength: 8, maxLength: 8 },
    { name: 'Ethiopia', flag: '/flags/eth.png', code: 'ET', dial_code: '+251', minLength: 9, maxLength: 9 },
    { name: 'Falkland Islands (Malvinas)', flag: '/flags/flk.png', code: 'FK', dial_code: '+500', minLength: 5, maxLength: 5 },
    { name: 'Faroe Islands', flag: '/flags/fro.png', code: 'FO', dial_code: '+298', minLength: 6, maxLength: 6 },
    { name: 'Fiji', flag: '/flags/fji.png', code: 'FJ', dial_code: '+679', minLength: 7, maxLength: 7 },
    { name: 'Finland', flag: '/flags/fin.png', code: 'FI', dial_code: '+358', minLength: 9, maxLength: 9 },
    { name: 'France', flag: '/flags/fra.png', code: 'FR', dial_code: '+33', minLength: 9, maxLength: 9 },
    { name: 'French Guiana', flag: '/flags/guf.png', code: 'GF', dial_code: '+594', minLength: 9, maxLength: 9 },
    { name: 'French Polynesia', flag: '/flags/pyf.png', code: 'PF', dial_code: '+689', minLength: 6, maxLength: 6 },
    { name: 'Gabon', flag: '/flags/gab.png', code: 'GA', dial_code: '+241', minLength: 8, maxLength: 8 },
    { name: 'Gambia', flag: '/flags/gmb.png', code: 'GM', dial_code: '+220', minLength: 7, maxLength: 7 },
    { name: 'Georgia', flag: '/flags/geo.png', code: 'GE', dial_code: '+995', minLength: 9, maxLength: 9 },
    { name: 'Germany', flag: '/flags/deu.png', code: 'DE', dial_code: '+49', minLength: 10, maxLength: 11 },
    { name: 'Ghana', flag: '/flags/gha.png', code: 'GH', dial_code: '+233', minLength: 9, maxLength: 9 },
    { name: 'Gibraltar', flag: '/flags/gib.png', code: 'GI', dial_code: '+350', minLength: 8, maxLength: 8 },
    { name: 'Greece', flag: '/flags/grc.png', code: 'GR', dial_code: '+30', minLength: 10, maxLength: 10 },
    { name: 'Greenland', flag: '/flags/grl.png', code: 'GL', dial_code: '+299', minLength: 6, maxLength: 6 },
    { name: 'Grenada', flag: '/flags/grd.png', code: 'GD', dial_code: '+1473', minLength: 7, maxLength: 7 },
    { name: 'Guadeloupe', flag: '/flags/glp.png', code: 'GP', dial_code: '+590', minLength: 9, maxLength: 9 },
    { name: 'Guam', flag: '/flags/gum.png', code: 'GU', dial_code: '+1671', minLength: 7, maxLength: 7 },
    { name: 'Guatemala', flag: '/flags/gtm.png', code: 'GT', dial_code: '+502', minLength: 8, maxLength: 8 },
    { name: 'Guernsey', flag: '/flags/ggy.png', code: 'GG', dial_code: '+44', minLength: 10, maxLength: 10 },
    { name: 'Guinea', flag: '/flags/gin.png', code: 'GN', dial_code: '+224', minLength: 9, maxLength: 9 },
    { name: 'Guinea-Bissau', flag: '/flags/gnb.png', code: 'GW', dial_code: '+245', minLength: 7, maxLength: 7 },
    { name: 'Guyana', flag: '/flags/guy.png', code: 'GY', dial_code: '+592', minLength: 7, maxLength: 7 },
    { name: 'Haiti', flag: '/flags/hti.png', code: 'HT', dial_code: '+509', minLength: 8, maxLength: 8 },
    { name: 'Holy See (Vatican City State)', flag: '/flags/vat.png', code: 'VA', dial_code: '+39', minLength: 10, maxLength: 10 },
    { name: 'Honduras', flag: '/flags/hnd.png', code: 'HN', dial_code: '+504', minLength: 8, maxLength: 8 },
    { name: 'Hong Kong', flag: '/flags/hkg.png', code: 'HK', dial_code: '+852', minLength: 8, maxLength: 8 },
    { name: 'Hungary', flag: '/flags/hun.png', code: 'HU', dial_code: '+36', minLength: 9, maxLength: 9 },
    { name: 'Iceland', flag: '/flags/isl.png', code: 'IS', dial_code: '+354', minLength: 7, maxLength: 7 },
    { name: 'India', flag: '/flags/ind.png', code: 'IN', dial_code: '+91', minLength: 10, maxLength: 10 },
    { name: 'Indonesia', flag: '/flags/idn.png', code: 'ID', dial_code: '+62', minLength: 10, maxLength: 13 },
    { name: 'Iran, Islamic Republic of', flag: '/flags/irn.png', code: 'IR', dial_code: '+98', minLength: 10, maxLength: 10 },
    { name: 'Iraq', flag: '/flags/irq.png', code: 'IQ', dial_code: '+964', minLength: 10, maxLength: 10 },
    { name: 'Ireland', flag: '/flags/irl.png', code: 'IE', dial_code: '+353', minLength: 9, maxLength: 9 },
    { name: 'Isle of Man', flag: '/flags/imn.png', code: 'IM', dial_code: '+44', minLength: 10, maxLength: 10 },
    { name: 'Israel', flag: '/flags/isr.png', code: 'IL', dial_code: '+972', minLength: 9, maxLength: 9 },
    { name: 'Italy', flag: '/flags/ita.png', code: 'IT', dial_code: '+39', minLength: 10, maxLength: 10 },
    { name: 'Jamaica', flag: '/flags/jam.png', code: 'JM', dial_code: '+1876', minLength: 7, maxLength: 7 },
    { name: 'Japan', flag: '/flags/jpn.png', code: 'JP', dial_code: '+81', minLength: 10, maxLength: 10 },
    { name: 'Jersey', flag: '/flags/jey.png', code: 'JE', dial_code: '+44', minLength: 10, maxLength: 10 },
    { name: 'Jordan', flag: '/flags/jor.png', code: 'JO', dial_code: '+962', minLength: 9, maxLength: 9 },
    { name: 'Kazakhstan', flag: '/flags/kaz.png', code: 'KZ', dial_code: '+7', minLength: 10, maxLength: 10 },
    { name: 'Kenya', flag: '/flags/ken.png', code: 'KE', dial_code: '+254', minLength: 9, maxLength: 9 },
    { name: 'Kiribati', flag: '/flags/kir.png', code: 'KI', dial_code: '+686', minLength: 5, maxLength: 5 },
    { name: "Korea, Democratic People's Republic of", flag: '/flags/prk.png', code: 'KP', dial_code: '+850', minLength: 10, maxLength: 10 },
    { name: 'Korea, Republic of', flag: '/flags/kor.png', code: 'KR', dial_code: '+82', minLength: 10, maxLength: 11 },
    { name: 'Kuwait', flag: '/flags/kwt.png', code: 'KW', dial_code: '+965', minLength: 8, maxLength: 8 },
    { name: 'Kyrgyzstan', flag: '/flags/kgz.png', code: 'KG', dial_code: '+996', minLength: 9, maxLength: 9 },
    { name: "Lao People's Democratic Republic", flag: '/flags/lao.png', code: 'LA', dial_code: '+856', minLength: 10, maxLength: 10 },
    { name: 'Latvia', flag: '/flags/lva.png', code: 'LV', dial_code: '+371', minLength: 8, maxLength: 8 },
    { name: 'Lebanon', flag: '/flags/lbn.png', code: 'LB', dial_code: '+961', minLength: 8, maxLength: 8 },
    { name: 'Lesotho', flag: '/flags/lso.png', code: 'LS', dial_code: '+266', minLength: 8, maxLength: 8 },
    { name: 'Liberia', flag: '/flags/lbr.png', code: 'LR', dial_code: '+231', minLength: 7, maxLength: 8 },
    { name: 'Libyan Arab Jamahiriya', flag: '/flags/lby.png', code: 'LY', dial_code: '+218', minLength: 9, maxLength: 9 },
    { name: 'Liechtenstein', flag: '/flags/lie.png', code: 'LI', dial_code: '+423', minLength: 7, maxLength: 7 },
    { name: 'Lithuania', flag: '/flags/ltu.png', code: 'LT', dial_code: '+370', minLength: 8, maxLength: 8 },
    { name: 'Luxembourg', flag: '/flags/lux.png', code: 'LU', dial_code: '+352', minLength: 9, maxLength: 9 },
    { name: 'Macao', flag: '/flags/mac.png', code: 'MO', dial_code: '+853', minLength: 8, maxLength: 8 },
    { name: 'Macedonia, The Former Yugoslav Republic of', flag: '/flags/mkd.png', code: 'MK', dial_code: '+389', minLength: 8, maxLength: 8 },
    { name: 'Madagascar', flag: '/flags/mdg.png', code: 'MG', dial_code: '+261', minLength: 9, maxLength: 9 },
    { name: 'Malawi', flag: '/flags/mwi.png', code: 'MW', dial_code: '+265', minLength: 9, maxLength: 9 },
    { name: 'Malaysia', flag: '/flags/mys.png', code: 'MY', dial_code: '+60', minLength: 9, maxLength: 10 },
    { name: 'Maldives', flag: '/flags/mdv.png', code: 'MV', dial_code: '+960', minLength: 7, maxLength: 7 },
    { name: 'Mali', flag: '/flags/mli.png', code: 'ML', dial_code: '+223', minLength: 8, maxLength: 8 },
    { name: 'Malta', flag: '/flags/mlt.png', code: 'MT', dial_code: '+356', minLength: 8, maxLength: 8 },
    { name: 'Marshall Islands', flag: '/flags/mhl.png', code: 'MH', dial_code: '+692', minLength: 7, maxLength: 7 },
    { name: 'Martinique', flag: '/flags/mtq.png', code: 'MQ', dial_code: '+596', minLength: 9, maxLength: 9 },
    { name: 'Mauritania', flag: '/flags/mrt.png', code: 'MR', dial_code: '+222', minLength: 8, maxLength: 8 },
    { name: 'Mauritius', flag: '/flags/mus.png', code: 'MU', dial_code: '+230', minLength: 8, maxLength: 8 },
    { name: 'Mayotte', flag: '/flags/myt.png', code: 'YT', dial_code: '+262', minLength: 9, maxLength: 9 },
    { name: 'Mexico', flag: '/flags/mex.png', code: 'MX', dial_code: '+52', minLength: 10, maxLength: 10 },
    { name: 'Micronesia, Federated States of', flag: '/flags/fsm.png', code: 'FM', dial_code: '+691', minLength: 7, maxLength: 7 },
    { name: 'Moldova, Republic of', flag: '/flags/mda.png', code: 'MD', dial_code: '+373', minLength: 8, maxLength: 8 },
    { name: 'Monaco', flag: '/flags/mco.png', code: 'MC', dial_code: '+377', minLength: 8, maxLength: 9 },
    { name: 'Mongolia', flag: '/flags/mng.png', code: 'MN', dial_code: '+976', minLength: 8, maxLength: 8 },
    { name: 'Montenegro', flag: '/flags/mne.png', code: 'ME', dial_code: '+382', minLength: 8, maxLength: 8 },
    { name: 'Montserrat', flag: '/flags/msr.png', code: 'MS', dial_code: '+1664', minLength: 7, maxLength: 7 },
    { name: 'Morocco', flag: '/flags/mar.png', code: 'MA', dial_code: '+212', minLength: 9, maxLength: 9 },
    { name: 'Mozambique', flag: '/flags/moz.png', code: 'MZ', dial_code: '+258', minLength: 9, maxLength: 9 },
    { name: 'Myanmar', flag: '/flags/mmr.png', code: 'MM', dial_code: '+95', minLength: 8, maxLength: 8 },
    { name: 'Namibia', flag: '/flags/nam.png', code: 'NA', dial_code: '+264', minLength: 9, maxLength: 9 },
    { name: 'Nauru', flag: '/flags/nru.png', code: 'NR', dial_code: '+674', minLength: 7, maxLength: 7 },
    { name: 'Nepal', flag: '/flags/npl.png', code: 'NP', dial_code: '+977', minLength: 10, maxLength: 10 },
    { name: 'Netherlands', flag: '/flags/nld.png', code: 'NL', dial_code: '+31', minLength: 9, maxLength: 9 },
    { name: 'Netherlands Antilles', flag: '/flags/bes.png', code: 'AN', dial_code: '+599', minLength: 7, maxLength: 8 },
    { name: 'New Caledonia', flag: '/flags/ncl.png', code: 'NC', dial_code: '+687', minLength: 6, maxLength: 6 },
    { name: 'New Zealand', flag: '/flags/nzl.png', code: 'NZ', dial_code: '+64', minLength: 9, maxLength: 10 },
    { name: 'Nicaragua', flag: '/flags/nic.png', code: 'NI', dial_code: '+505', minLength: 8, maxLength: 8 },
    { name: 'Niger', flag: '/flags/ner.png', code: 'NE', dial_code: '+227', minLength: 8, maxLength: 8 },
    { name: 'Nigeria', flag: '/flags/nga.png', code: 'NG', dial_code: '+234', minLength: 10, maxLength: 10 },
    { name: 'Niue', flag: '/flags/niu.png', code: 'NU', dial_code: '+683', minLength: 4, maxLength: 4 },
    { name: 'Norfolk Island', flag: '/flags/nfk.png', code: 'NF', dial_code: '+672', minLength: 6, maxLength: 6 },
    { name: 'Northern Mariana Islands', flag: '/flags/mnp.png', code: 'MP', dial_code: '+1670', minLength: 7, maxLength: 7 },
    { name: 'Norway', flag: '/flags/nor.png', code: 'NO', dial_code: '+47', minLength: 8, maxLength: 8 },
    { name: 'Oman', flag: '/flags/omn.png', code: 'OM', dial_code: '+968', minLength: 8, maxLength: 8 },
    { name: 'Pakistan', flag: '/flags/pak.png', code: 'PK', dial_code: '+92', minLength: 10, maxLength: 10 },
    { name: 'Palau', flag: '/flags/plw.png', code: 'PW', dial_code: '+680', minLength: 7, maxLength: 7 },
    { name: 'Palestinian Territory, Occupied', flag: '/flags/pse.png', code: 'PS', dial_code: '+970', minLength: 9, maxLength: 9 },
    { name: 'Panama', flag: '/flags/pan.png', code: 'PA', dial_code: '+507', minLength: 8, maxLength: 8 },
    { name: 'Papua New Guinea', flag: '/flags/png.png', code: 'PG', dial_code: '+675', minLength: 8, maxLength: 8 },
    { name: 'Paraguay', flag: '/flags/pry.png', code: 'PY', dial_code: '+595', minLength: 9, maxLength: 9 },
    { name: 'Peru', flag: '/flags/per.png', code: 'PE', dial_code: '+51', minLength: 9, maxLength: 9 },
    { name: 'Philippines', flag: '/flags/phl.png', code: 'PH', dial_code: '+63', minLength: 10, maxLength: 10 },
    { name: 'Pitcairn', flag: '/flags/pcn.png', code: 'PN', dial_code: '+870', minLength: 9, maxLength: 9 },
    { name: 'Poland', flag: '/flags/pol.png', code: 'PL', dial_code: '+48', minLength: 9, maxLength: 9 },
    { name: 'Portugal', flag: '/flags/prt.png', code: 'PT', dial_code: '+351', minLength: 9, maxLength: 9 },
    { name: 'Puerto Rico', flag: '/flags/pri.png', code: 'PR', dial_code: '+1', minLength: 10, maxLength: 10 },
    { name: 'Qatar', flag: '/flags/qat.png', code: 'QA', dial_code: '+974', minLength: 8, maxLength: 8 },
    { name: 'Reunion', flag: '/flags/reu.png', code: 'RE', dial_code: '+262', minLength: 9, maxLength: 9 },
    { name: 'Romania', flag: '/flags/rou.png', code: 'RO', dial_code: '+40', minLength: 9, maxLength: 9 },
    { name: 'Russian Federation', flag: '/flags/rus.png', code: 'RU', dial_code: '+7', minLength: 10, maxLength: 10 },
    { name: 'Rwanda', flag: '/flags/rwa.png', code: 'RW', dial_code: '+250', minLength: 9, maxLength: 9 },
    { name: 'Saint Helena', flag: '/flags/shn.png', code: 'SH', dial_code: '+290', minLength: 4, maxLength: 4 },
    { name: 'Saint Kitts and Nevis', flag: '/flags/kna.png', code: 'KN', dial_code: '+1869', minLength: 7, maxLength: 7 },
    { name: 'Saint Lucia', flag: '/flags/lca.png', code: 'LC', dial_code: '+1758', minLength: 7, maxLength: 7 },
    { name: 'Saint Pierre and Miquelon', flag: '/flags/spm.png', code: 'PM', dial_code: '+508', minLength: 6, maxLength: 6 },
    { name: 'Saint Vincent and the Grenadines', flag: '/flags/vct.png', code: 'VC', dial_code: '+1784', minLength: 7, maxLength: 7 },
    { name: 'Samoa', flag: '/flags/wsm.png', code: 'WS', dial_code: '+685', minLength: 7, maxLength: 7 },
    { name: 'San Marino', flag: '/flags/smr.png', code: 'SM', dial_code: '+378', minLength: 10, maxLength: 10 },
    { name: 'Sao Tome and Principe', flag: '/flags/stp.png', code: 'ST', dial_code: '+239', minLength: 7, maxLength: 7 },
    { name: 'Saudi Arabia', flag: '/flags/sau.png', code: 'SA', dial_code: '+966', minLength: 9, maxLength: 9 },
    { name: 'Senegal', flag: '/flags/sen.png', code: 'SN', dial_code: '+221', minLength: 9, maxLength: 9 },
    { name: 'Serbia', flag: '/flags/srb.png', code: 'RS', dial_code: '+381', minLength: 9, maxLength: 9 },
    { name: 'Seychelles', flag: '/flags/syc.png', code: 'SC', dial_code: '+248', minLength: 7, maxLength: 7 },
    { name: 'Sierra Leone', flag: '/flags/sle.png', code: 'SL', dial_code: '+232', minLength: 8, maxLength: 8 },
    { name: 'Singapore', flag: '/flags/sgp.png', code: 'SG', dial_code: '+65', minLength: 8, maxLength: 8 },
    { name: 'Slovakia', flag: '/flags/svk.png', code: 'SK', dial_code: '+421', minLength: 9, maxLength: 9 },
    { name: 'Slovenia', flag: '/flags/svn.png', code: 'SI', dial_code: '+386', minLength: 8, maxLength: 8 },
    { name: 'Solomon Islands', flag: '/flags/slb.png', code: 'SB', dial_code: '+677', minLength: 7, maxLength: 7 },
    { name: 'Somalia', flag: '/flags/som.png', code: 'SO', dial_code: '+252', minLength: 8, maxLength: 8 },
    { name: 'South Africa', flag: '/flags/zaf.png', code: 'ZA', dial_code: '+27', minLength: 9, maxLength: 9 },
    { name: 'Spain', flag: '/flags/esp.png', code: 'ES', dial_code: '+34', minLength: 9, maxLength: 9 },
    { name: 'Sri Lanka', flag: '/flags/lka.png', code: 'LK', dial_code: '+94', minLength: 9, maxLength: 9 },
    { name: 'Sudan', flag: '/flags/sdn.png', code: 'SD', dial_code: '+249', minLength: 9, maxLength: 9 },
    { name: 'Suriname', flag: '/flags/sur.png', code: 'SR', dial_code: '+597', minLength: 7, maxLength: 7 },
    { name: 'Svalbard and Jan Mayen', flag: '/flags/sjm.png', code: 'SJ', dial_code: '+47', minLength: 8, maxLength: 8 },
    { name: 'Swaziland', flag: '/flags/swz.png', code: 'SZ', dial_code: '+268', minLength: 8, maxLength: 8 },
    { name: 'Sweden', flag: '/flags/swe.png', code: 'SE', dial_code: '+46', minLength: 9, maxLength: 9 },
    { name: 'Switzerland', flag: '/flags/che.png', code: 'CH', dial_code: '+41', minLength: 9, maxLength: 9 },
    { name: 'Syrian Arab Republic', flag: '/flags/syr.png', code: 'SY', dial_code: '+963', minLength: 9, maxLength: 9 },
    { name: 'Taiwan, Province of China', flag: '/flags/twn.png', code: 'TW', dial_code: '+886', minLength: 9, maxLength: 9 },
    { name: 'Tajikistan', flag: '/flags/tjk.png', code: 'TJ', dial_code: '+992', minLength: 9, maxLength: 9 },
    { name: 'Tanzania, United Republic of', flag: '/flags/tza.png', code: 'TZ', dial_code: '+255', minLength: 9, maxLength: 9 },
    { name: 'Thailand', flag: '/flags/tha.png', code: 'TH', dial_code: '+66', minLength: 9, maxLength: 9 },
    { name: 'Timor-Leste', flag: '/flags/tls.png', code: 'TL', dial_code: '+670', minLength: 8, maxLength: 8 },
    { name: 'Togo', flag: '/flags/tgo.png', code: 'TG', dial_code: '+228', minLength: 8, maxLength: 8 },
    { name: 'Tokelau', flag: '/flags/tkl.png', code: 'TK', dial_code: '+690', minLength: 4, maxLength: 4 },
    { name: 'Tonga', flag: '/flags/ton.png', code: 'TO', dial_code: '+676', minLength: 5, maxLength: 5 },
    { name: 'Trinidad and Tobago', flag: '/flags/tto.png', code: 'TT', dial_code: '+1868', minLength: 7, maxLength: 7 },
    { name: 'Tunisia', flag: '/flags/tun.png', code: 'TN', dial_code: '+216', minLength: 8, maxLength: 8 },
    { name: 'Turkey', flag: '/flags/tur.png', code: 'TR', dial_code: '+90', minLength: 10, maxLength: 10 },
    { name: 'Turkmenistan', flag: '/flags/tkm.png', code: 'TM', dial_code: '+993', minLength: 8, maxLength: 8 },
    { name: 'Turks and Caicos Islands', flag: '/flags/tca.png', code: 'TC', dial_code: '+1649', minLength: 7, maxLength: 7 },
    { name: 'Tuvalu', flag: '/flags/tuv.png', code: 'TV', dial_code: '+688', minLength: 5, maxLength: 5 },
    { name: 'Uganda', flag: '/flags/uga.png', code: 'UG', dial_code: '+256', minLength: 9, maxLength: 9 },
    { name: 'Ukraine', flag: '/flags/ukr.png', code: 'UA', dial_code: '+380', minLength: 9, maxLength: 9 },
    { name: 'United Arab Emirates', flag: '/flags/are.png', code: 'AE', dial_code: '+971', minLength: 9, maxLength: 9 },
    { name: 'United Kingdom', flag: '/flags/gbr.png', code: 'GB', dial_code: '+44', minLength: 10, maxLength: 10 },
    { name: 'United States', flag: '/flags/usa.png', code: 'US', dial_code: '+1', minLength: 10, maxLength: 10 },
    { name: 'Uruguay', flag: '/flags/ury.png', code: 'UY', dial_code: '+598', minLength: 8, maxLength: 8 },
    { name: 'Uzbekistan', flag: '/flags/uzb.png', code: 'UZ', dial_code: '+998', minLength: 9, maxLength: 9 },
    { name: 'Vanuatu', flag: '/flags/vut.png', code: 'VU', dial_code: '+678', minLength: 7, maxLength: 7 },
    { name: 'Venezuela', flag: '/flags/ven.png', code: 'VE', dial_code: '+58', minLength: 10, maxLength: 10 },
    { name: 'Vietnam', flag: '/flags/vnm.png', code: 'VN', dial_code: '+84', minLength: 9, maxLength: 9 },
    { name: 'Virgin Islands, British', flag: '/flags/vgb.png', code: 'VG', dial_code: '+1284', minLength: 7, maxLength: 7 },
    { name: 'Virgin Islands, U.S.', flag: '/flags/vir.png', code: 'VI', dial_code: '+1340', minLength: 7, maxLength: 7 },
    { name: 'Wallis and Futuna', flag: '/flags/wlf.png', code: 'WF', dial_code: '+681', minLength: 6, maxLength: 6 },
    { name: 'Yemen', flag: '/flags/yem.png', code: 'YE', dial_code: '+967', minLength: 9, maxLength: 9 },
    { name: 'Zambia', flag: '/flags/zmb.png', code: 'ZM', dial_code: '+260', minLength: 9, maxLength: 9 },
    { name: 'Zimbabwe', flag: '/flags/zwe.png', code: 'ZW', dial_code: '+263', minLength: 9, maxLength: 9 }
];
